### ISSUE TITLE
You can download all pretrained weights of yolo_series with Baidu Drive (YOLO)

### ISSUE THREAD

**Issue by aWindTalker** [Mobu59/yolo_series#1]
You can download all pretrained weights of yolo_series with [Baidu Drive (YOLO)](https://pan.baidu.com/s/1Ws4Aieyt7gne9nrCK7VHJA)
大佬，这个提取码能不能提供一下？【拜托】

**Comment by Mobu59** [comment]
提取码就是YOLO呀

**Comment by Mobu59** [comment]
> You can download all pretrained weights of yolo_series with [Baidu Drive (YOLO)](https://pan.baidu.com/s/1Ws4Aieyt7gne9nrCK7VHJA) 大佬，这个提取码能不能提供一下？【拜托】

代码的话建议用github上的YOLOU 我是在他的上面改了一点点

**Comment by aWindTalker** [comment]
谢谢！😂
